version: '3.8'

services:
  # Backend: Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - mariadb
    networks:
      - app-network
    command: [sh, -c, "composer install && php artisan serve --host=0.0.0.0 --port=8000"]

  # MariaDB
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - app-network

  # Frontend: Vue 3
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: [sh, -c, "npm install && npm run dev"]
    image: node:22-alpine
    working_dir: /usr/app
    volumes:
      - ./frontend:/usr/app/
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
